
stages:
  - lint
  - build
  - test
    
.base_job:
  image: registry.larrycloud.ca/qawse3dr/plant-tracker:latest 

Lint:
  extends: .base_job
  stage: lint
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make test-format
  allow_failure: true
  
#########################################
#                                       #
#       PLANT TRACKER SERVER            #
#                                       #
#########################################
Build Plant Tracker Server:
  extends: .base_job
  stage: build
  script:
    - cd server
    - chmod +x ./gradlew
    - ./gradlew jar
    - mkdir -p ../out
    - mv app/build/libs/plant-tracker.jar ../out
    - cp app/src/main/resources/config.json ../out
  artifacts:
    paths:
      - out/
    expire_in: 1 week

Test Plant Tracker Server:
  extends: .base_job
  stage: test
  script:
    - cd server
    - chmod +x gradlew
    - ./gradlew test


#########################################
#                                       #
#           PLANT LISTENER              #
#                                       #
#########################################
Build Plant Listener Tests:
  extends: .base_job
  stage: build
  artifacts:
    paths:
      - build
    expire_in: 1 week
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=test
    - make -j4

Build Plant Listener:
  image: registry.larrycloud.ca/qawse3dr/plant-tracker-rpi-zero:latest  
  extends: .base_job
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=release -DCMAKE_TOOLCHAIN_FILE=/home/develop/opt/x-tools/armv6-rpi-linux-gnueabihf/armv6-rpi-linux-gnueabihf.toolchain.cmake ..
    - make -j4
    - mkdir -p ../out/plant_listener
    - mv ./bin ../out/plant_listener
    - mv ./lib ../out/plant_listener
    - mv ../plant_listener/data/config.json ../out/plant_listener
  artifacts:
    paths:
      - out/plant_listener
    expire_in: 1 week


Test Coverage Plant Listener:
  extends: .base_job
  stage: test
  dependencies:
    - Build Plant Listener Tests
  artifacts:
    paths:
      - out/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: out/coverage.xml
  script:
    - cd build
    - ctest --output-on-failure
    - make plantlistener_coverage
    - cd ..
    - mkdir out
    - mv build/coverage out/coverage
    - mv build/coverage.xml out/coverage.xml

#########################################
#                                       #
#        PLANT TRACKER ANDROID          #
#                                       #
#########################################
Build Android Plant Tracker Debug:
  image: registry.larrycloud.ca/qawse3dr/plant-tracker-android:latest
  stage: build
  variables:
    BUILD_PLANT_LISTENER: 0
  script:
    - mkdir -p build
    - echo "${GOOGLE_SERVICES_JSON}" > ./android/plant_tracker/app/google-services.json
    - cd build
    - cmake ..
    - make PlantTracker
  artifacts:
    paths:
      - build/app
    expire_in: 1 week
