
stages:
  - lint
  - build
  - test
    
.base_job:
  image: registry.larrycloud.ca/qawse3dr/plant-tracker:latest 

Lint:
  extends: .base_job
  stage: lint
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make test-format
  allow_failure: true


  
#########################################
#                                       #
#       PLANT TRACKER SERVER            #
#                                       #
#########################################
Build Plant Tracker Server:
  extends: .base_job
  stage: build
  script:
    - echo "TODO"

# TODO will need to make my own build container to support building for RPI
# Build Plant Listener:
#   image: gcc 
#   extends: .base_job
#   stage: build
#   script:
#     - echo "TODO"


#########################################
#                                       #
#           PLANT LISTENER              #
#                                       #
#########################################
Build Plant Listener Tests:
  extends: .base_job
  stage: build
  artifacts:
    paths:
      - build
    expire_in: 1 week
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=test
    - make -j4


Test Plant Listener:
  extends: .base_job
  stage: test
  dependencies:
    - Build Plant Listener Tests
  script:
    - cd build
    - make test

#########################################
#                                       #
#        PLANT TRACKER ANDROID          #
#                                       #
#########################################
Build Android Plant Tracker Debug:
  image: registry.larrycloud.ca/qawse3dr/plant-tracker-android:latest
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make PlantTracker
  artifacts:
    paths:
      - build/app
    expire_in: 1 week
